name: Test application

on:
  push:
    branches: 
      - 'dev'
    paths: 
      - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
          
      - name: Install dependencies
        run: go get -v -t -d ./...
        
      - name: Build
        run: go build -v ./...
        
      - name: Test with the Go CLI
        run: go test ./...
